export type AdminModuleKey = "catalog" | "orders" | "quote_request" | "finance" | "fiscal" | "customers" | "content" | "marketing" | "delivery" | "integrations";
export type AdminModuleAccess = "full" | "limited" | "view" | "none";
export type AdminPermission = "*" | `${string}.${string}`;

export type PermissionProfile = {
  id: string;
  slug: string;
  name: string;
  description: string;
  level: number;
  isSystem: boolean;
  isActive: boolean;
  permissions: AdminPermission[];
  aliases?: string[];
  modules: Array<{
    key: AdminModuleKey;
    label: string;
    access: AdminModuleAccess;
  }>;
};

const permissionProfiles = [
  {
    id: "admin_master",
    slug: "admin_master",
    name: "Admin master",
    description: "Acesso completo a operacao, configuracoes, catalogo e integracoes.",
    level: 100,
    isSystem: true,
    isActive: true,
    permissions: ["*"],
    modules: [
      { key: "catalog", label: "Catalogo", access: "full" },
      { key: "quote_request", label: "Solicitacoes de orcamento", access: "full" },
      { key: "orders", label: "Pedidos", access: "full" },
      { key: "finance", label: "Financeiro", access: "full" },
      { key: "fiscal", label: "Fiscal", access: "full" },
      { key: "customers", label: "Clientes e leads", access: "full" },
      { key: "content", label: "Conteudo", access: "full" },
      { key: "marketing", label: "Marketing e campanhas", access: "full" },
      { key: "delivery", label: "Entrega e retirada", access: "full" },
      { key: "integrations", label: "Integracoes", access: "full" },
    ],
  },
  {
    id: "gerente_ecommerce",
    slug: "gerente_ecommerce",
    aliases: ["ecommerce_operations_manager"],
    name: "Gerente de ecommerce",
    description: "Coordena operacao diaria, pedidos, atendimento, expedicao, indicadores e go/no-go operacional.",
    level: 90,
    isSystem: true,
    isActive: true,
    permissions: [
      "dashboard.view",
      "orders.view",
      "orders.edit",
      "orders.update_status",
      "orders.assign_owner",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "orders.advance_stage",
      "orders.export",
      "quote_request.view",
      "quote_request.update_status",
      "quote_request.assign_responsible",
      "quote_request.notes_create",
      "quote_request.export",
      "customers.view",
      "catalog.view",
      "catalog.create",
      "catalog.edit",
      "catalog.approve",
      "categories.view",
      "categories.edit",
      "categories.manage",
      "products.media_manage",
      "products.seo_edit",
      "banners.view",
      "banners.edit",
      "banners.manage",
      "marketing.view",
      "marketing.manage",
      "campaigns.manage",
      "themes.manage",
      "showcases.manage",
      "pages.view",
      "pages.edit",
      "support.view",
      "support.manage",
      "reports.sales_view",
      "reports.products_view",
      "reports.operations_view",
      "reports.catalog_quality_view",
      "carts.view",
      "audit.operation_view",
      "shipping.view",
      "shipping.update_status",
      "stock.view",
      "stock.validate_availability",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "limited" },
      { key: "quote_request", label: "Solicitacoes de orcamento", access: "full" },
      { key: "orders", label: "Pedidos", access: "full" },
      { key: "finance", label: "Financeiro", access: "view" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "full" },
      { key: "content", label: "Conteudo", access: "view" },
      { key: "marketing", label: "Marketing e campanhas", access: "full" },
      { key: "delivery", label: "Entrega e retirada", access: "limited" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "gestor_comercial",
    slug: "gestor_comercial",
    aliases: ["commercial_manager"],
    name: "Gestor comercial",
    description: "Opera vendas, conversao, showroom, leads, atendimento comercial e performance.",
    level: 80,
    isSystem: true,
    isActive: true,
    permissions: [
      "dashboard.commercial_view",
      "orders.view",
      "quote_request.view",
      "quote_request.update_status",
      "quote_request.assign_responsible",
      "quote_request.notes_create",
      "customers.view",
      "catalog.view",
      "stock.view",
      "stock.view_public",
      "support.view",
      "support.manage",
      "reports.sales_view",
      "reports.customers_view",
      "reports.products_view",
      "carts.view",
      "coupons.view",
      "coupons.apply",
      "marketing.view",
      "campaigns.edit",
      "coupons.manage",
      "orders.internal_note",
      "orders.assign_owner",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "commercial.notes_manage",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "limited" },
      { key: "quote_request", label: "Solicitacoes de orcamento", access: "full" },
      { key: "orders", label: "Pedidos", access: "full" },
      { key: "finance", label: "Financeiro", access: "view" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "full" },
      { key: "content", label: "Conteudo", access: "view" },
      { key: "marketing", label: "Marketing e campanhas", access: "limited" },
      { key: "delivery", label: "Entrega e retirada", access: "limited" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "operador_pedidos",
    slug: "operador_pedidos",
    aliases: ["order_operator"],
    name: "Operador de pedidos",
    description: "Atualiza status, registra acoes manuais e acompanha pagamentos e expedicao.",
    level: 50,
    isSystem: true,
    isActive: true,
    permissions: [
      "orders.view",
      "orders.update_status",
      "orders.internal_note",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "orders.print",
      "customers.view_basic",
      "payments.view_status",
      "shipping.view_status",
      "shipping.view",
      "support.create_ticket",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Pedidos", access: "full" },
      { key: "finance", label: "Financeiro", access: "view" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "limited" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "view" },
      { key: "delivery", label: "Entrega e retirada", access: "limited" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "fiscal_contador",
    slug: "fiscal_contador",
    aliases: ["fiscal_accountant"],
    name: "Fiscal e contador",
    description: "Fecha classificacao fiscal, acompanha documentos fiscais, readiness fiscal e homologacao tributaria.",
    level: 60,
    isSystem: true,
    isActive: true,
    permissions: [
      "orders.view_paid",
      "fiscal.view",
      "fiscal.edit",
      "fiscal.export",
      "customers.view_fiscal",
      "products.view_fiscal",
      "reports.fiscal_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Pedidos", access: "limited" },
      { key: "finance", label: "Financeiro", access: "view" },
      { key: "fiscal", label: "Fiscal", access: "full" },
      { key: "customers", label: "Clientes e leads", access: "none" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "none" },
      { key: "delivery", label: "Entrega e retirada", access: "view" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "supervisor_loja",
    slug: "supervisor_loja",
    aliases: ["store_supervisor"],
    name: "Supervisor de loja",
    description: "Acompanha pedidos da loja, vendedores, retirada, separacao e atendimento operacional.",
    level: 70,
    isSystem: true,
    isActive: true,
    permissions: [
      "orders.view",
      "orders.operational_note",
      "orders.release_to_picking",
      "orders.assign_owner",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "orders.advance_stage",
      "stock.view",
      "stock.validate_availability",
      "stock.report_issue",
      "shipping.view",
      "shipping.manage",
      "shipping.update_status",
      "reports.operations_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "limited" },
      { key: "orders", label: "Pedidos", access: "full" },
      { key: "finance", label: "Financeiro", access: "view" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "limited" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "view" },
      { key: "delivery", label: "Entrega e retirada", access: "limited" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "caixa_financeiro",
    slug: "caixa_financeiro",
    aliases: ["cashier_finance"],
    name: "Caixa e financeiro",
    description: "Confere pagamentos, conciliacao, acao manual de cobranca e pedidos aguardando pagamento.",
    level: 65,
    isSystem: true,
    isActive: true,
    permissions: [
      "orders.view",
      "payments.view",
      "payments.confirm",
      "payments.reject",
      "payments.refund_request",
      "payments.conciliation",
      "reports.financial_view",
      "reports.sales_view",
      "finance.export",
      "orders.financial_note",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "orders.advance_stage",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Pedidos", access: "limited" },
      { key: "finance", label: "Financeiro", access: "full" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "view" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "view" },
      { key: "delivery", label: "Entrega e retirada", access: "none" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
  {
    id: "separacao_expedicao",
    slug: "separacao_expedicao",
    aliases: ["separation_expedition"],
    name: "Separacao e expedicao",
    description: "Opera fila de separacao, conferencia, despacho, retirada em loja e rastreio.",
    level: 35,
    isSystem: true,
    isActive: true,
    permissions: [
      "orders.view_released",
      "orders.print",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "orders.advance_stage",
      "shipping.view",
      "shipping.update_status",
      "shipping.add_note",
      "shipping.attach_proof",
      "stock.report_issue",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Pedidos", access: "limited" },
      { key: "finance", label: "Financeiro", access: "none" },
      { key: "fiscal", label: "Fiscal", access: "none" },
      { key: "customers", label: "Clientes e leads", access: "view" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "none" },
      { key: "delivery", label: "Entrega e retirada", access: "limited" },
      { key: "integrations", label: "Integracoes", access: "none" },
    ],
  },
  {
    id: "catalogo_conteudo",
    slug: "catalogo_conteudo",
    aliases: ["catalog_content"],
    name: "Catalogo e conteudo",
    description: "Atualiza produtos, categorias, marcas, banners e paginas institucionais.",
    level: 45,
    isSystem: true,
    isActive: true,
    permissions: [
      "catalog.view",
      "catalog.create",
      "catalog.edit",
      "catalog.submit_for_approval",
      "categories.view",
      "categories.edit",
      "products.media_manage",
      "products.seo_edit",
      "banners.view",
      "banners.edit",
      "marketing.view",
      "campaigns.edit",
      "themes.edit",
      "showcases.edit",
      "pages.view",
      "pages.edit",
      "reports.catalog_quality_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "full" },
      { key: "orders", label: "Pedidos", access: "view" },
      { key: "finance", label: "Financeiro", access: "none" },
      { key: "fiscal", label: "Fiscal", access: "view" },
      { key: "customers", label: "Clientes e leads", access: "none" },
      { key: "content", label: "Conteudo", access: "full" },
      { key: "marketing", label: "Marketing e campanhas", access: "limited" },
      { key: "delivery", label: "Entrega e retirada", access: "view" },
      { key: "integrations", label: "Integracoes", access: "none" },
    ],
  },
  {
    id: "atendimento_suporte",
    slug: "atendimento_suporte",
    aliases: ["support_agent"],
    name: "Atendimento e suporte",
    description: "Opera leads, tickets, devolucoes e relacionamento com o cliente.",
    level: 40,
    isSystem: true,
    isActive: true,
    permissions: [
      "customers.view",
      "customers.edit_contact",
      "orders.view_customer_orders",
      "support.view",
      "support.manage",
      "support.create_ticket",
      "support.internal_note",
      "orders.mark_stuck",
      "orders.resolve_stuck",
      "catalog.view",
      "stock.view_public",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Pedidos", access: "limited" },
      { key: "finance", label: "Financeiro", access: "none" },
      { key: "fiscal", label: "Fiscal", access: "none" },
      { key: "customers", label: "Clientes e leads", access: "full" },
      { key: "content", label: "Conteudo", access: "none" },
      { key: "marketing", label: "Marketing e campanhas", access: "view" },
      { key: "delivery", label: "Entrega e retirada", access: "view" },
      { key: "integrations", label: "Integracoes", access: "view" },
    ],
  },
] as const satisfies readonly PermissionProfile[];

const deniedPermissionProfile: PermissionProfile = {
  id: "__invalid__",
  slug: "__invalid__",
  name: "Perfil invalido",
  description: "Perfil inexistente ou inativo. Acesso negado por padrao.",
  level: 0,
  isSystem: true,
  isActive: false,
  permissions: [],
  modules: [
    { key: "catalog", label: "Catalogo", access: "none" },
    { key: "orders", label: "Pedidos", access: "none" },
    { key: "finance", label: "Financeiro", access: "none" },
    { key: "fiscal", label: "Fiscal", access: "none" },
    { key: "customers", label: "Clientes e leads", access: "none" },
    { key: "content", label: "Conteudo", access: "none" },
    { key: "marketing", label: "Marketing e campanhas", access: "none" },
    { key: "delivery", label: "Entrega e retirada", access: "none" },
    { key: "integrations", label: "Integracoes", access: "none" },
  ],
};

const phase1PermissionProfiles = [
  {
    id: "administrador",
    slug: "administrador",
    aliases: ["admin_master", "admin"],
    name: "Administrador",
    description: "Acesso completo aos modulos ativos da Fase 1 da GAMEL.",
    level: 100,
    isSystem: true,
    isActive: true,
    permissions: ["*"],
    modules: [
      { key: "catalog", label: "Catalogo", access: "full" },
      { key: "quote_request", label: "Solicitacoes de orcamento", access: "full" },
      { key: "orders", label: "Orcamentos e leads", access: "full" },
      { key: "finance", label: "Modulo futuro", access: "none" },
      { key: "fiscal", label: "Modulo futuro", access: "none" },
      { key: "customers", label: "Leads", access: "full" },
      { key: "content", label: "Conteudo", access: "full" },
      { key: "marketing", label: "Banners e vitrines", access: "full" },
      { key: "delivery", label: "Modulo futuro", access: "none" },
      { key: "integrations", label: "Usuarios e go-live", access: "full" },
    ],
  },
  {
    id: "comercial",
    slug: "comercial",
    aliases: ["gestor_comercial", "atendimento_suporte", "operador_pedidos"],
    name: "Comercial",
    description: "Atende orcamentos, leads e registros de WhatsApp dentro do fluxo comercial assistido.",
    level: 70,
    isSystem: true,
    isActive: true,
    permissions: [
      "dashboard.view",
      "orders.view",
      "orders.edit",
      "orders.internal_note",
      "orders.assign_owner",
      "orders.update_status",
      "orders.advance_stage",
      "orders.resolve_stuck",
      "orders.release_to_picking",
      "orders.financial_note",
      "orders.operational_note",
      "shipping.update_status",
      "support.internal_note",
      "quote_request.view",
      "quote_request.update_status",
      "quote_request.assign_responsible",
      "quote_request.notes_create",
      "customers.view",
      "customers.edit_contact",
      "support.view",
      "support.manage",
      "catalog.view",
      "stock.view_public",
      "reports.sales_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "quote_request", label: "Solicitacoes de orcamento", access: "full" },
      { key: "orders", label: "Orcamentos e leads", access: "full" },
      { key: "finance", label: "Modulo futuro", access: "none" },
      { key: "fiscal", label: "Modulo futuro", access: "none" },
      { key: "customers", label: "Leads", access: "full" },
      { key: "content", label: "Conteudo", access: "view" },
      { key: "marketing", label: "Banners e vitrines", access: "view" },
      { key: "delivery", label: "Modulo futuro", access: "none" },
      { key: "integrations", label: "Usuarios e go-live", access: "view" },
    ],
  },
  {
    id: "catalogo_conteudo",
    slug: "catalogo_conteudo",
    aliases: ["catalog_content"],
    name: "Catalogo/Conteudo",
    description: "Gerencia produtos, categorias, descricoes, imagens, alt text e publicacao do catalogo.",
    level: 60,
    isSystem: true,
    isActive: true,
    permissions: [
      "catalog.view",
      "catalog.create",
      "catalog.edit",
      "catalog.submit_for_approval",
      "catalog.approve",
      "categories.view",
      "categories.edit",
      "categories.manage",
      "products.media_manage",
      "products.seo_edit",
      "pages.view",
      "pages.edit",
      "reports.catalog_quality_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "full" },
      { key: "orders", label: "Orcamentos e leads", access: "view" },
      { key: "finance", label: "Modulo futuro", access: "none" },
      { key: "fiscal", label: "Modulo futuro", access: "none" },
      { key: "customers", label: "Leads", access: "view" },
      { key: "content", label: "Conteudo", access: "full" },
      { key: "marketing", label: "Banners e vitrines", access: "limited" },
      { key: "delivery", label: "Modulo futuro", access: "none" },
      { key: "integrations", label: "Usuarios e go-live", access: "view" },
    ],
  },
  {
    id: "marketing",
    slug: "marketing",
    aliases: ["marketing_content"],
    name: "Marketing",
    description: "Gerencia banners, vitrines, campanhas institucionais e CTAs da Fase 1.",
    level: 50,
    isSystem: true,
    isActive: true,
    permissions: [
      "marketing.view",
      "marketing.manage",
      "campaigns.edit",
      "banners.view",
      "banners.edit",
      "banners.manage",
      "showcases.edit",
      "showcases.manage",
      "pages.view",
      "reports.products_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Orcamentos e leads", access: "view" },
      { key: "finance", label: "Modulo futuro", access: "none" },
      { key: "fiscal", label: "Modulo futuro", access: "none" },
      { key: "customers", label: "Leads", access: "view" },
      { key: "content", label: "Conteudo", access: "limited" },
      { key: "marketing", label: "Banners e vitrines", access: "full" },
      { key: "delivery", label: "Modulo futuro", access: "none" },
      { key: "integrations", label: "Usuarios e go-live", access: "view" },
    ],
  },
  {
    id: "visualizacao_diretoria",
    slug: "visualizacao_diretoria",
    aliases: ["diretoria", "executive_view"],
    name: "Visualizacao/Diretoria",
    description: "Acesso de leitura para acompanhamento de catalogo, leads e prontidao de go-live.",
    level: 30,
    isSystem: true,
    isActive: true,
    permissions: [
      "dashboard.view",
      "catalog.view",
      "orders.view",
      "customers.view",
      "marketing.view",
      "reports.sales_view",
      "reports.products_view",
      "reports.catalog_quality_view",
    ],
    modules: [
      { key: "catalog", label: "Catalogo", access: "view" },
      { key: "orders", label: "Orcamentos e leads", access: "view" },
      { key: "finance", label: "Modulo futuro", access: "none" },
      { key: "fiscal", label: "Modulo futuro", access: "none" },
      { key: "customers", label: "Leads", access: "view" },
      { key: "content", label: "Conteudo", access: "view" },
      { key: "marketing", label: "Banners e vitrines", access: "view" },
      { key: "delivery", label: "Modulo futuro", access: "none" },
      { key: "integrations", label: "Usuarios e go-live", access: "view" },
    ],
  },
] as const satisfies readonly PermissionProfile[];

export function getPermissionProfiles(): readonly PermissionProfile[] {
  return phase1PermissionProfiles;
}

export function normalizePermissionProfileId(profileId?: string | null) {
  const profile = getPermissionProfile(profileId);
  return profile.id;
}

export function getPermissionProfile(profileId?: string | null): PermissionProfile {
  if (!profileId) return deniedPermissionProfile;
  return (
    phase1PermissionProfiles.find(
      (profile) => profile.id === profileId || profile.slug === profileId || Boolean((profile.aliases as readonly string[] | undefined)?.includes(String(profileId || ""))),
    ) ?? deniedPermissionProfile
  );
}

export function canAdminPerform(profileId: string | null | undefined, permission: AdminPermission) {
  const profile = getPermissionProfile(profileId);
  if (!profile.isActive) return false;
  if (profile.permissions.includes("*")) return true;
  const equivalentPermissions: Record<string, AdminPermission[]> = {
    "quote_request.read": ["quote_request.view"],
    "quote_request.read_detail": ["quote_request.view"],
    "quote_request.assign": ["quote_request.assign_responsible"],
    "quote_request.add_note": ["quote_request.notes_create"],
    "quote_request.archive": ["quote_request.update_status"],
    "quote_request.view": ["quote_request.read", "quote_request.read_detail"],
    "quote_request.assign_responsible": ["quote_request.assign"],
    "quote_request.notes_create": ["quote_request.add_note"],
  };
  const accepted = [permission, ...(equivalentPermissions[permission] ?? [])];
  return accepted.some((entry) => profile.permissions.includes(entry));
}

export function hasAdminLevel(profileId: string | null | undefined, minimumLevel: number) {
  return getPermissionProfile(profileId).level >= minimumLevel;
}

export function canAdminAccessModule(profileId: string | null | undefined, moduleKey: AdminModuleKey, minimumAccess: Exclude<AdminModuleAccess, "none"> = "view") {
  const rank: Record<AdminModuleAccess, number> = {
    none: 0,
    view: 1,
    limited: 2,
    full: 3,
  };

  const profile = getPermissionProfile(profileId);
  const module = profile.modules.find((entry) => entry.key === moduleKey);
  if (!module) return false;
  return rank[module.access] >= rank[minimumAccess];
}
