ALTER TABLE IF EXISTS banners
  ADD COLUMN IF NOT EXISTS subtitle TEXT,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS cta_label TEXT,
  ADD COLUMN IF NOT EXISTS linked_product_slug TEXT,
  ADD COLUMN IF NOT EXISTS linked_campaign_slug TEXT,
  ADD COLUMN IF NOT EXISTS show_on_home BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS show_on_totem BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS show_on_vitrine BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS starts_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ends_at TIMESTAMPTZ;

ALTER TABLE IF EXISTS campaigns
  ADD COLUMN IF NOT EXISTS gallery_media_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS totem_media_id TEXT,
  ADD COLUMN IF NOT EXISTS vitrine_media_id TEXT;

ALTER TABLE IF EXISTS totem_settings
  ADD COLUMN IF NOT EXISTS intro_title TEXT,
  ADD COLUMN IF NOT EXISTS intro_subtitle TEXT,
  ADD COLUMN IF NOT EXISTS hero_media_id TEXT,
  ADD COLUMN IF NOT EXISTS category_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS featured_product_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS campaign_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS banner_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];

ALTER TABLE IF EXISTS vitrine_settings
  ADD COLUMN IF NOT EXISTS hero_media_id TEXT,
  ADD COLUMN IF NOT EXISTS show_qr_codes BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS layout_mode TEXT NOT NULL DEFAULT 'automatico',
  ADD COLUMN IF NOT EXISTS campaign_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS product_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
  ADD COLUMN IF NOT EXISTS banner_slugs TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
