/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as TotemRouteImport } from './routes/totem'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as OfertasRouteImport } from './routes/ofertas'
import { Route as CatalogoRouteImport } from './routes/catalogo'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProdutoSlugRouteImport } from './routes/produto.$slug'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as CampanhaSlugRouteImport } from './routes/campanha.$slug'
import { Route as AdminVitrineTvRouteImport } from './routes/admin.vitrine-tv'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminTotemRouteImport } from './routes/admin.totem'
import { Route as AdminSeoAgendamentosRouteImport } from './routes/admin.seo-agendamentos'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminRelatoriosRouteImport } from './routes/admin.relatorios'
import { Route as AdminQrcodesRouteImport } from './routes/admin.qrcodes'
import { Route as AdminProdutosRouteImport } from './routes/admin.produtos'
import { Route as AdminMidiaRouteImport } from './routes/admin.midia'
import { Route as AdminLojaRouteImport } from './routes/admin.loja'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminConteudoRouteImport } from './routes/admin.conteudo'
import { Route as AdminConfiguracoesTecnicasRouteImport } from './routes/admin.configuracoes-tecnicas'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'
import { Route as AdminCampanhasRouteImport } from './routes/admin.campanhas'
import { Route as ApiPublicMediaRouteImport } from './routes/api/public/media'
import { Route as ApiPublicTelemetryLeadsRouteImport } from './routes/api/public/telemetry/leads'
import { Route as ApiPublicTelemetryEventsRouteImport } from './routes/api/public/telemetry/events'
import { Route as ApiPublicCronSeoAuditRouteImport } from './routes/api/public/cron.seo-audit'
import { Route as ApiAdminMediaUploadRouteImport } from './routes/api/admin/media/upload'

const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const TotemRoute = TotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertasRoute = OfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoRoute = CatalogoRouteImport.update({
  id: '/catalogo',
  path: '/catalogo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProdutoSlugRoute = ProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhaSlugRoute = CampanhaSlugRouteImport.update({
  id: '/campanha/$slug',
  path: '/campanha/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVitrineTvRoute = AdminVitrineTvRouteImport.update({
  id: '/vitrine-tv',
  path: '/vitrine-tv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTotemRoute = AdminTotemRouteImport.update({
  id: '/totem',
  path: '/totem',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoAgendamentosRoute = AdminSeoAgendamentosRouteImport.update({
  id: '/seo-agendamentos',
  path: '/seo-agendamentos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminQrcodesRoute = AdminQrcodesRouteImport.update({
  id: '/qrcodes',
  path: '/qrcodes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMidiaRoute = AdminMidiaRouteImport.update({
  id: '/midia',
  path: '/midia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLojaRoute = AdminLojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesTecnicasRoute =
  AdminConfiguracoesTecnicasRouteImport.update({
    id: '/configuracoes-tecnicas',
    path: '/configuracoes-tecnicas',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCampanhasRoute = AdminCampanhasRouteImport.update({
  id: '/campanhas',
  path: '/campanhas',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicMediaRoute = ApiPublicMediaRouteImport.update({
  id: '/api/public/media',
  path: '/api/public/media',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryLeadsRoute = ApiPublicTelemetryLeadsRouteImport.update({
  id: '/api/public/telemetry/leads',
  path: '/api/public/telemetry/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryEventsRoute =
  ApiPublicTelemetryEventsRouteImport.update({
    id: '/api/public/telemetry/events',
    path: '/api/public/telemetry/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronSeoAuditRoute = ApiPublicCronSeoAuditRouteImport.update({
  id: '/api/public/cron/seo-audit',
  path: '/api/public/cron/seo-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminMediaUploadRoute = ApiAdminMediaUploadRouteImport.update({
  id: '/api/admin/media/upload',
  path: '/api/admin/media/upload',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/totem': typeof TotemRoute
  '/vitrine': typeof VitrineRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes-tecnicas': typeof AdminConfiguracoesTecnicasRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-agendamentos': typeof AdminSeoAgendamentosRoute
  '/admin/totem': typeof AdminTotemRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vitrine-tv': typeof AdminVitrineTvRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/public/cron/seo-audit': typeof ApiPublicCronSeoAuditRoute
  '/api/public/telemetry/events': typeof ApiPublicTelemetryEventsRoute
  '/api/public/telemetry/leads': typeof ApiPublicTelemetryLeadsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalogo': typeof CatalogoRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/totem': typeof TotemRoute
  '/vitrine': typeof VitrineRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes-tecnicas': typeof AdminConfiguracoesTecnicasRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-agendamentos': typeof AdminSeoAgendamentosRoute
  '/admin/totem': typeof AdminTotemRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vitrine-tv': typeof AdminVitrineTvRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/public/cron/seo-audit': typeof ApiPublicCronSeoAuditRoute
  '/api/public/telemetry/events': typeof ApiPublicTelemetryEventsRoute
  '/api/public/telemetry/leads': typeof ApiPublicTelemetryLeadsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/catalogo': typeof CatalogoRoute
  '/ofertas': typeof OfertasRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/totem': typeof TotemRoute
  '/vitrine': typeof VitrineRoute
  '/admin/campanhas': typeof AdminCampanhasRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/configuracoes-tecnicas': typeof AdminConfiguracoesTecnicasRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/loja': typeof AdminLojaRoute
  '/admin/midia': typeof AdminMidiaRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/qrcodes': typeof AdminQrcodesRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/seo-agendamentos': typeof AdminSeoAgendamentosRoute
  '/admin/totem': typeof AdminTotemRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/admin/vitrine-tv': typeof AdminVitrineTvRoute
  '/campanha/$slug': typeof CampanhaSlugRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/produto/$slug': typeof ProdutoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/media': typeof ApiPublicMediaRoute
  '/api/admin/media/upload': typeof ApiAdminMediaUploadRoute
  '/api/public/cron/seo-audit': typeof ApiPublicCronSeoAuditRoute
  '/api/public/telemetry/events': typeof ApiPublicTelemetryEventsRoute
  '/api/public/telemetry/leads': typeof ApiPublicTelemetryLeadsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/catalogo'
    | '/ofertas'
    | '/sitemap.xml'
    | '/totem'
    | '/vitrine'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/configuracoes-tecnicas'
    | '/admin/conteudo'
    | '/admin/login'
    | '/admin/loja'
    | '/admin/midia'
    | '/admin/produtos'
    | '/admin/qrcodes'
    | '/admin/relatorios'
    | '/admin/seo'
    | '/admin/seo-agendamentos'
    | '/admin/totem'
    | '/admin/usuarios'
    | '/admin/vitrine-tv'
    | '/campanha/$slug'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/api/public/media'
    | '/api/admin/media/upload'
    | '/api/public/cron/seo-audit'
    | '/api/public/telemetry/events'
    | '/api/public/telemetry/leads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalogo'
    | '/ofertas'
    | '/sitemap.xml'
    | '/totem'
    | '/vitrine'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/configuracoes-tecnicas'
    | '/admin/conteudo'
    | '/admin/login'
    | '/admin/loja'
    | '/admin/midia'
    | '/admin/produtos'
    | '/admin/qrcodes'
    | '/admin/relatorios'
    | '/admin/seo'
    | '/admin/seo-agendamentos'
    | '/admin/totem'
    | '/admin/usuarios'
    | '/admin/vitrine-tv'
    | '/campanha/$slug'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin'
    | '/api/public/media'
    | '/api/admin/media/upload'
    | '/api/public/cron/seo-audit'
    | '/api/public/telemetry/events'
    | '/api/public/telemetry/leads'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/catalogo'
    | '/ofertas'
    | '/sitemap.xml'
    | '/totem'
    | '/vitrine'
    | '/admin/campanhas'
    | '/admin/categorias'
    | '/admin/configuracoes-tecnicas'
    | '/admin/conteudo'
    | '/admin/login'
    | '/admin/loja'
    | '/admin/midia'
    | '/admin/produtos'
    | '/admin/qrcodes'
    | '/admin/relatorios'
    | '/admin/seo'
    | '/admin/seo-agendamentos'
    | '/admin/totem'
    | '/admin/usuarios'
    | '/admin/vitrine-tv'
    | '/campanha/$slug'
    | '/categoria/$slug'
    | '/produto/$slug'
    | '/admin/'
    | '/api/public/media'
    | '/api/admin/media/upload'
    | '/api/public/cron/seo-audit'
    | '/api/public/telemetry/events'
    | '/api/public/telemetry/leads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CatalogoRoute: typeof CatalogoRoute
  OfertasRoute: typeof OfertasRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TotemRoute: typeof TotemRoute
  VitrineRoute: typeof VitrineRoute
  CampanhaSlugRoute: typeof CampanhaSlugRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  ProdutoSlugRoute: typeof ProdutoSlugRoute
  ApiPublicMediaRoute: typeof ApiPublicMediaRoute
  ApiAdminMediaUploadRoute: typeof ApiAdminMediaUploadRoute
  ApiPublicCronSeoAuditRoute: typeof ApiPublicCronSeoAuditRoute
  ApiPublicTelemetryEventsRoute: typeof ApiPublicTelemetryEventsRoute
  ApiPublicTelemetryLeadsRoute: typeof ApiPublicTelemetryLeadsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totem': {
      id: '/totem'
      path: '/totem'
      fullPath: '/totem'
      preLoaderRoute: typeof TotemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ofertas': {
      id: '/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof OfertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo': {
      id: '/catalogo'
      path: '/catalogo'
      fullPath: '/catalogo'
      preLoaderRoute: typeof CatalogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/produto/$slug': {
      id: '/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof ProdutoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanha/$slug': {
      id: '/campanha/$slug'
      path: '/campanha/$slug'
      fullPath: '/campanha/$slug'
      preLoaderRoute: typeof CampanhaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vitrine-tv': {
      id: '/admin/vitrine-tv'
      path: '/vitrine-tv'
      fullPath: '/admin/vitrine-tv'
      preLoaderRoute: typeof AdminVitrineTvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/totem': {
      id: '/admin/totem'
      path: '/totem'
      fullPath: '/admin/totem'
      preLoaderRoute: typeof AdminTotemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo-agendamentos': {
      id: '/admin/seo-agendamentos'
      path: '/seo-agendamentos'
      fullPath: '/admin/seo-agendamentos'
      preLoaderRoute: typeof AdminSeoAgendamentosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/qrcodes': {
      id: '/admin/qrcodes'
      path: '/qrcodes'
      fullPath: '/admin/qrcodes'
      preLoaderRoute: typeof AdminQrcodesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/midia': {
      id: '/admin/midia'
      path: '/midia'
      fullPath: '/admin/midia'
      preLoaderRoute: typeof AdminMidiaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/loja': {
      id: '/admin/loja'
      path: '/loja'
      fullPath: '/admin/loja'
      preLoaderRoute: typeof AdminLojaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes-tecnicas': {
      id: '/admin/configuracoes-tecnicas'
      path: '/configuracoes-tecnicas'
      fullPath: '/admin/configuracoes-tecnicas'
      preLoaderRoute: typeof AdminConfiguracoesTecnicasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/campanhas': {
      id: '/admin/campanhas'
      path: '/campanhas'
      fullPath: '/admin/campanhas'
      preLoaderRoute: typeof AdminCampanhasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/media': {
      id: '/api/public/media'
      path: '/api/public/media'
      fullPath: '/api/public/media'
      preLoaderRoute: typeof ApiPublicMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/leads': {
      id: '/api/public/telemetry/leads'
      path: '/api/public/telemetry/leads'
      fullPath: '/api/public/telemetry/leads'
      preLoaderRoute: typeof ApiPublicTelemetryLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry/events': {
      id: '/api/public/telemetry/events'
      path: '/api/public/telemetry/events'
      fullPath: '/api/public/telemetry/events'
      preLoaderRoute: typeof ApiPublicTelemetryEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/seo-audit': {
      id: '/api/public/cron/seo-audit'
      path: '/api/public/cron/seo-audit'
      fullPath: '/api/public/cron/seo-audit'
      preLoaderRoute: typeof ApiPublicCronSeoAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/media/upload': {
      id: '/api/admin/media/upload'
      path: '/api/admin/media/upload'
      fullPath: '/api/admin/media/upload'
      preLoaderRoute: typeof ApiAdminMediaUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCampanhasRoute: typeof AdminCampanhasRoute
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConfiguracoesTecnicasRoute: typeof AdminConfiguracoesTecnicasRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminLojaRoute: typeof AdminLojaRoute
  AdminMidiaRoute: typeof AdminMidiaRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminQrcodesRoute: typeof AdminQrcodesRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminSeoAgendamentosRoute: typeof AdminSeoAgendamentosRoute
  AdminTotemRoute: typeof AdminTotemRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminVitrineTvRoute: typeof AdminVitrineTvRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCampanhasRoute: AdminCampanhasRoute,
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConfiguracoesTecnicasRoute: AdminConfiguracoesTecnicasRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminLojaRoute: AdminLojaRoute,
  AdminMidiaRoute: AdminMidiaRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminQrcodesRoute: AdminQrcodesRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminSeoAgendamentosRoute: AdminSeoAgendamentosRoute,
  AdminTotemRoute: AdminTotemRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminVitrineTvRoute: AdminVitrineTvRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CatalogoRoute: CatalogoRoute,
  OfertasRoute: OfertasRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TotemRoute: TotemRoute,
  VitrineRoute: VitrineRoute,
  CampanhaSlugRoute: CampanhaSlugRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  ProdutoSlugRoute: ProdutoSlugRoute,
  ApiPublicMediaRoute: ApiPublicMediaRoute,
  ApiAdminMediaUploadRoute: ApiAdminMediaUploadRoute,
  ApiPublicCronSeoAuditRoute: ApiPublicCronSeoAuditRoute,
  ApiPublicTelemetryEventsRoute: ApiPublicTelemetryEventsRoute,
  ApiPublicTelemetryLeadsRoute: ApiPublicTelemetryLeadsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
